assets:
  - wordpress.sql.gz
steps:
  - name: Testing
    script: |
      true
      echo "That exited $?"
      false
      echo "That exited $?"
  - name: Test Build
    plugin: WordPressApp
    subDirectory: 'www'
    database: wordpress.sql.gz
    databaseGzipped: true
