assets:
  - wordpress.sql.gz
steps:
  - name: Test Build
    plugin: WordPressApp
    subDirectory: 'www'
    database: wordpress.sql.gz
    databaseGzipped: true
    updatePlugins: true
    flushCaches: false
  - name: Echo the things
    plugin: Shell
    command: 'echo "Hello World!"'
  - name: Test Step
    command: printf '\033[0;31m [This should be red like a rose] \033[0m'
